import { OnInit, EventEmitter } from '@angular/core';
import { CalendarEvent } from '../../interfaces/calendar-event.interface';
import { MDBModalService, MDBModalRef } from 'angular-bootstrap-md';
import { CalendarView } from '../../uilts/calendar-view';
import { MdbCalendarOptions } from '../../interfaces/calendar-options.interface';
export declare class MdbCalendarComponent implements OnInit {
    private modalService;
    weekDaysDefault: string[];
    weekDaysShortDefault: string[];
    monthsDefault: string[];
    monthsShortDefault: string[];
    calendarOptions: MdbCalendarOptions;
    dayLabels: string[];
    dayLabelsShort: string[];
    weekDayIndex: number;
    events: CalendarEvent[];
    options: MdbCalendarOptions;
    editable: boolean;
    weekDays: string[];
    weekDaysShort: string[];
    months: string[];
    monthsShort: string[];
    defaultView: CalendarView;
    eventDeleted: EventEmitter<CalendarEvent>;
    eventEdited: EventEmitter<CalendarEvent>;
    eventAdded: EventEmitter<CalendarEvent>;
    monthChanged: EventEmitter<any>;
    weekChanged: EventEmitter<any>;
    listChanged: EventEmitter<any>;
    modalRef: MDBModalRef;
    MS_IN_DAY: number;
    view: typeof CalendarView;
    currentView: CalendarView;
    constructor(modalService: MDBModalService);
    ngOnInit(): void;
    private _changeDaysOrder;
    getFormattedEvent(event: CalendarEvent): {
        id: string;
        name: string;
        startDate: string;
        endDate: string;
        color: string;
    };
    formatDate(date: Date): void;
    onDayClick(day: any): void;
    onEventClick(event: CalendarEvent): void;
    onViewChange(view: string): void;
    onMonthChange(event: any): void;
    onWeekChange(event: any): void;
    onListChange(event: any): void;
    openAddModal(event: CalendarEvent): void;
    openEditModal(event: CalendarEvent): void;
}
